### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Scrincz** [YuLin12345/Affordable-AIO-Bot#4]
Hey, really became interesting in this since running across it and have a couple questions. First being how do you think it will perform compared to other bots on the market along with how long do you think it may take to complete? Other then that best of luck and you might see a couple of cups of coffee coming your way.

**Comment by YuLin12345** [comment]
I have not worked on this for a very long time. I do not have time to work on it. As for the performance, it will depends on how I implement/code the functions.

Thanks
